## load du lieu

In [4]:
from sklearn import datasets
import pandas as pd
import numpy as np

In [13]:
iris = datasets.load_iris()
X = iris['data']
y = iris['target']

## data selecting

In [16]:
# lua chon 2 features de de truc quan tren khong gian 2 chieu
X = X[: , [0, 2]]

## train test split

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size=0.3,
                                                    stratify=y)

In [23]:
np.bincount(y)

array([50, 50, 50], dtype=int64)

In [24]:
np.bincount(y_train), np.bincount(y_test)

(array([35, 35, 35], dtype=int64), array([15, 15, 15], dtype=int64))

## EDA

### shape

In [28]:
X_train.shape

(105, 2)

### peak to peak, ptp
khoang gia tri, max - min

In [46]:
np.ptp(X, axis=0, keepdims=False)

array([3.6, 5.9])

In [48]:
np.ptp(X, axis=1, keepdims=True)

array([[3.7],
       [3.5],
       [3.4],
       [3.1],
       [3.6],
       [3.7],
       [3.2],
       [3.5],
       [3. ],
       [3.4],
       [3.9],
       [3.2],
       [3.4],
       [3.2],
       [4.6],
       [4.2],
       [4.1],
       [3.7],
       [4. ],
       [3.6],
       [3.7],
       [3.6],
       [3.6],
       [3.4],
       [2.9],
       [3.4],
       [3.4],
       [3.7],
       [3.8],
       [3.1],
       [3.2],
       [3.9],
       [3.7],
       [4.1],
       [3.4],
       [3.8],
       [4.2],
       [3.5],
       [3.1],
       [3.6],
       [3.7],
       [3.2],
       [3.1],
       [3.4],
       [3.2],
       [3.4],
       [3.5],
       [3.2],
       [3.8],
       [3.6],
       [2.3],
       [1.9],
       [2. ],
       [1.5],
       [1.9],
       [1.2],
       [1.6],
       [1.6],
       [2. ],
       [1.3],
       [1.5],
       [1.7],
       [2. ],
       [1.4],
       [2. ],
       [2.3],
       [1.1],
       [1.7],
       [1.7],
       [1.7],
       [1.1],
      

In [49]:
np.ptp(X)

6.9

### percentile

In [54]:
np.percentile(X, [25, 50, 75], axis=0, keepdims=False)

array([[5.1 , 1.6 ],
       [5.8 , 4.35],
       [6.4 , 5.1 ]])

In [55]:
np.median(X, axis=0)

array([5.8 , 4.35])

In [56]:
np.nanpercentile(X, [25, 50, 75], axis=0, keepdims=False)

array([[5.1 , 1.6 ],
       [5.8 , 4.35],
       [6.4 , 5.1 ]])

## quantile

In [57]:
np.quantile(X, [0.25, 0.5, 0.75], axis=0, keepdims=False)

array([[5.1 , 1.6 ],
       [5.8 , 4.35],
       [6.4 , 5.1 ]])

# visualization

In [25]:
import matplotlib.pyplot as plt
%matplotlib inline